#!/bin/bash
mkdir -p sections/{section1,section2,section3,section4,section5,section6,section7,section8,section9,appendices}
mv overview.html sections/section1/
mv indications.html sections/section1/
mv contraindications.html sections/section1/
mv equipment.html sections/section2/
mv placement-screen.html sections/section2/
mv insertion-procedure.html sections/section3/
mv staffing.html sections/section4/
mv icu-checkin.html sections/section5/
mv nursing-management.html sections/section5/
mv purge-fluid-change.html sections/section5/
mv escalation.html sections/section6/
mv weaning.html sections/section7/
mv removal.html sections/section7/
mv position-alarms.html sections/section8/
mv purge-alarms.html sections/section8/
mv flow-suction.html sections/section8/
mv haemolysis.html sections/section8/
mv hit.html sections/section8/
mv nursing-training.html sections/section9/
mv physician-training.html sections/section9/
mv spr-training.html sections/section9/
mv algorithm.html sections/appendices/
mv candidacy.html sections/appendices/
mv echo-repositioning.html sections/appendices/
mv distal-perfusion.html sections/appendices/
rm _template.html 2>/dev/null
echo "✓ Done!"
